libstdc++: Add initializers for constexpr static data members in Node
In the CL https://crrev.com/c/6512733 static constexpr data members of
structs ParentNodeTag and ShadowHostTag were added without initializers.
But C++ standard requires initializer for constexpr static data member
of LiteralType. So, added missing initializers for these structs.

Without this change the build fails with GCC compiler errors like:
../../third_party/blink/renderer/core/dom/node.h:1261:5: error: 'constexpr' static data member 'kParentNodeTag' must have an initializer

Bug: 41455655
Change-Id: Id273e4f85b6052dd28bd36003e8a2b6ea8dd061c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6867590
Reviewed-by: Joey Arhar <jarhar@chromium.org>
Reviewed-by: Mason Freed <masonf@chromium.org>
Commit-Queue: Mason Freed <masonf@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1505983}
NOKEYCHECK=True
GitOrigin-RevId: 8a92ef07e3ded9e8ecfdeb484aac9e0ce60aa7ea