QuotaExceededError: Update QuotaExceededError instances
This change updates services that use QuotaExceededError
to use the new DOMException derived QuotaExceededError class
when the flag is enabled.

I've not been allowed to update external wpts until the webidl
spec has been updated[0][1], so this change only updates tests for
Chrome only wpts, and otherwise updates expectations for
the external ones. External wpts will be updated when the
webidl spec is merged and I am allowed to update the external
wpts (as seen in chained CL).

[0] Spec PR: https://github.com/whatwg/webidl/pull/1465
[1] Discussion: https://github.com/web-platform-tests/wpt/pull/52571#issuecomment-2884515600

Bug: 406162261
Change-Id: Ie45d6095a3e4c21e21a35d2519d268580b8bc36b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6538066
Commit-Queue: Ayu Ishii <ayui@chromium.org>
Reviewed-by: Daseul Lee <dslee@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1463139}
NOKEYCHECK=True
GitOrigin-RevId: a7bea0c1732f6ab4caedaa0739b1f9ba8949d7f2