QuotaExceededError: Update leftover QuotaExceededError instances
This change updates left over places that use the QuotaExceededError
to use the new DOMException derived QuotaExceededError class
when the flag is enabled. Changes in other services were made
in https://crrev.com/c/6538066.

Bug: 406162261
Change-Id: I1198782c738641d2006981e530314e7fc5daad9f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6594136
Commit-Queue: Ayu Ishii <ayui@chromium.org>
Reviewed-by: Joey Arhar <jarhar@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1467196}
NOKEYCHECK=True
GitOrigin-RevId: 9519e6150130354e13bfdd3ff4926d50a7c5f9a0