[ios wpt]: Fix ios wptrunner error due to a missing library.
Error shows as:
ModuleNotFoundError: No module named 'exception_occurrences_pb2'

Change-Id: I46cfeee8c28cb7ae8dc88be55d9830ae3153ccea
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5626915
Reviewed-by: Yue She <yueshe@google.com>
Reviewed-by: Weizhong Xia <weizhong@google.com>
Commit-Queue: Jie Sheng <jiesheng@google.com>
Cr-Commit-Position: refs/heads/main@{#1314176}
NOKEYCHECK=True
GitOrigin-RevId: 25267c3c8bb0a00d56cfef5bb9d8dcedf154e937