WebUI: Update TypeScript compiler from 5.8.2 to 5.9.3, part 2.
- Updating typescript to 5.9.3 (which requires all steps listed below)
- Updating all '@typescript-eslint/...' deps 8.26.0 -> 8.46.1, which
  is necessary for them to work with the latest TypeScript compiler
  version.
- Temporarily turning off
  @typescript-eslint/no-unnecessary-type-assertion ESLint check to
  silence newly surfaced errors due to HTMLElement#textContent no longer
  marked as nullable. The plan is to re-enable this after this CL lands
  along with the necessary fixes across the codebase.
- Updating third_party/node/patches/typescript.patch to apply cleanly.

ImageCapture API
- Remove 'w3c-image-capture' from the tsconfig 'types' field where it
  was causing new 'error TS2300: Duplicate identifier ...' errors due to
  the ImageCapture API being now part of TypeScript's lib.dom.d.ts.
- Add ImageCapture#grabFrame in
  tools/typescript/definitions/pending.d.ts since it is missing from
  lib.dom.d.ts
- Fix newly surfaced errors related to the ImageCapture API usage since
  most of its interfaces have all optional properties, unlike
 'w3c-image-capture'.
- Disable @typescript-eslint/no-non-null-assertion in
  ash/webui/camera_app_ui/ temporarily to unblock the fixes above.
  Owners of that folder should follow-up with a proper fix and re-enable
  it.

Bug: 451650623
Change-Id: Ifa3df6e8e63c9e9bae03c782764654db398ccf5a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7046349
Reviewed-by: Teresa Mao <temao@chromium.org>
Commit-Queue: Demetrios Papadopoulos <dpapad@chromium.org>
Reviewed-by: Mike Dougherty <michaeldo@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1531084}
NOKEYCHECK=True
GitOrigin-RevId: 526ce480702488dd484234f8b7b55adfcf619177