Fix missing deps for obj/third_party/blink/renderer/core/exported/exported/web_view_impl.oo
ukai@ukai ...src/chromium/src % cat out/siso-android/args.gn

android_static_analysis = "off"
coverage_instrumentation_input_file = "//.code-coverage/files_to_instrument.txt"
dcheck_always_on = true
debuggable_apks = false
enable_chrome_android_internal = false
fail_on_android_expectations = true
ffmpeg_branding = "Chrome"
is_component_build = false
is_debug = false
proprietary_codecs = true
strip_debug_info = true
symbol_level = 0
system_webview_package_name = "com.google.android.apps.chrome"
target_cpu = "arm64"
target_os = "android"
use_clang_coverage = true
use_reclient = false
use_remoteexec = true
use_siso = true

ukai@ukai ...src/chromium/src % gn clean out/siso-android

ukai@ukai ...src/chromium/src % SISO_EXPERIMENTS=fail-on-bad-deps siso ninja --verbose_failures=false -C out/siso-android obj/third_party/blink/renderer/core/exported/exported/web_view_impl.o

ninja: Entering directory `out/siso-android'
reapi instance: projects/rbe-chrome-untrusted/instances/default_instance
 3.67s load siso config
SISO_EXPERIMENTS=fail-on-bad-deps enabled
 5.88s Regenerating ninja files
 4.41s reloading
[6538/6539] 2m29.63s F CXX obj/third_p...core/exported/exported/web_view_impl.o
FAILED: f33a86d0-72d7-41b0-a34e-985ce64b7c75 "./obj/third_party/blink/renderer/core/exported/exported/web_view_impl.o" CXX obj/third_party/blink/renderer/core/exported/exported/web_view_impl.o
err: exit=1
"python3" ../../build/toolchain/clang_code_coverage_wrapper.py -  ...(too long)
Use '--verbose_failures' to see the command lines
build step: cxx "./obj/third_party/blink/renderer/core/exported/exported/web_view_impl.o"
siso_rule: clang-coverage/cxx
stderr:
In file included from ../../third_party/blink/renderer/core/exported/web_view_impl.cc:152:
../../third_party/blink/renderer/core/page/chrome_client_impl.h:42:10: fatal error: 'third_party/blink/renderer/core/buildflags.h' file not found
   42 | #include "third_party/blink/renderer/core/buildflags.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

build failed
local:1243 remote:4121 cache:1175 fallback:0 retry:0 skip:3854
reapi: ops: 13742(err:4306) / r:30649(err:0) 586.93MiB / w:11843(err:0) 581.85MiB
fs: ops: 625344(err:143801) / r:77250(err:0) 2.96GiB / w:27613(err:0) 710.44MiB
    resource/capa used(err)  wait-avg |   s m |  serv-avg |   s m |
        rbe:sched   4121(0)     2.90s |▂▂▂█   |     2.44s |  ▂█▂▂ |
       rbe:worker   4121(0)     0.62s |   █▂  |     1.82s |  ▅█▂▂ |
 remoteexec/10240   4121(0)     0.00s |█      |     7.32s |   █▃▂ |

2m30.14s Build Failure: 6539 done 1 failed 0 remaining - 43.55/s
 1 steps failed: exit=1
see ./out/siso-android/siso_output for full command line and output
 or ./out/siso-android/siso.INFO
use ./out/siso-android/siso_failed_commands.sh to re-run failed commands

Bug: 422309501
Change-Id: Id518300753de45ed0752cf4d24309caae733f0bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6626248
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
Reviewed-by: Joey Arhar <jarhar@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1472147}
NOKEYCHECK=True
GitOrigin-RevId: 71f2ce08b402d43bdbcab6489c8de51c69d8db64