Add missing dependency to probe_nocompile_tests
When compiling
`obj/third_party/blink/renderer/core/probe/probe_nocompile_tests/probe_nocompile_placeholder.o`,
there is an error due to a missing deps.

error: 'expected-error' diagnostics seen but not expected:
  File ../../third_party/blink/renderer/platform/heap/persistent.h Line 8: 'third_party/blink/renderer/platform/heap/heap_buildflags.h' file not found

Bug: 1480969
Change-Id: I634a252b3d60a682c29d98176ea60a59c7a2edef
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5011237
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Reviewed-by: Andrey Kosyakov <caseq@chromium.org>
Commit-Queue: Choongwoo Han <choongwoo.han@microsoft.com>
Cr-Commit-Position: refs/heads/main@{#1223913}
NOKEYCHECK=True
GitOrigin-RevId: bc71ede6e6f1c7fc306104749731363b79fd9538