Revert "Uprev material_web_components to 1.0.0"
This reverts commit 1f6484ae3820f25439f7ecf762b5346ccf5e8270.

Reason for revert: Bots seems to be failing with:

Error: Could not load ash_clang_x64/gen/ui/webui/resources/tsc/mwc/@material/web/focus/md-focus-ring.js (imported by ash_clang_x64/gen/ui/webui/resources/tsc/mwc/@material/web/switch/internal/switch.js): ENOENT: no such file or directory, open 'ash_clang_x64/gen/ui/webui/resources/tsc/mwc/@material/web/focus/md-focus-ring.js'

Original change's description:
> Uprev material_web_components to 1.0.0
>
> Change-Id: I46c13b5862212ff775503854ec58b94735d04ba7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4929529
> Commit-Queue: Meredith Lane <meredithl@chromium.org>
> Reviewed-by: Zain Afzal <zafzal@google.com>
> Cr-Commit-Position: refs/heads/main@{#1208077}

Change-Id: I52e421965afd50de7a1732caac43d39572469306
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4930592
Auto-Submit: Giovanni Ortuno Urquidi <ortuno@chromium.org>
Commit-Queue: Zain Afzal <zafzal@google.com>
Reviewed-by: Zain Afzal <zafzal@google.com>
Cr-Commit-Position: refs/heads/main@{#1208088}
NOKEYCHECK=True
GitOrigin-RevId: dd7090302d19aa2e1174b94767acd45088411e56