Revert "Do not lint deleted files"
This reverts commit cec570ed94d843eb407d2fdcd593b0ba8dbca4e1.

Reason for revert: Caused failure on linux-presubmit bot.
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8736591731489252177/+/u/presubmit/stdout

```
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/linux_presubmit/src/third_party/blink/web_tests/external/PRESUBMIT_test.py", line 128, in testWPTLintErrors
    errors = PRESUBMIT._LintWPT(mock_input, mock_output)
  File "/b/s/w/ir/cache/builder/linux_presubmit/src/third_party/blink/web_tests/external/PRESUBMIT.py", line 26, in _LintWPT
    return lint_wpt_root(input_api, output_api, wpt_path)
  File "/b/s/w/ir/cache/builder/linux_presubmit/src/third_party/blink/web_tests/external/../../tools/blinkpy/presubmit/common_checks.py", line 22, in lint_wpt_root
    for af in input_api.AffectedFiles(include_deletes=False):
AttributeError: 'MockInputApi' object has no attribute 'AffectedFiles'
```

Original change's description:
> Do not lint deleted files
>
> This is causing a lint error on Windows when there are renames.
>
> A more complete fix is to lint all files when committing, as some lint
> errors can leak in if we only lint changed or new files.
>
> Bug: None
> Change-Id: I0d589770d92e8288abbb49c17706c04ec0ad3c0f
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5868078
> Reviewed-by: Jonathan Lee <jonathanjlee@google.com>
> Commit-Queue: Weizhong Xia <weizhong@google.com>
> Cr-Commit-Position: refs/heads/main@{#1356207}

Bug: None
Change-Id: I299f8724c38ffb0f11d5048a2305070a45bca41d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5869289
Reviewed-by: Yuki Shiino <yukishiino@chromium.org>
Commit-Queue: Tsuyoshi Horo <horo@chromium.org>
Owners-Override: Tsuyoshi Horo <horo@chromium.org>
Auto-Submit: Tsuyoshi Horo <horo@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1356243}
NOKEYCHECK=True
GitOrigin-RevId: f839eb8c24b3fbad2d5b7c4bc93f5b588209a5c0