Remove unused variable 'mask_halpha'
when build for loongarch, it will produce compile error like below:
error: unused variable 'mask_halpha' [-Werror,-Wunused-variable]
  v4u32 mask_halpha = __lsx_vreplgr2vr_w(0xff000000);
        ^

so we should remove it.

Change-Id: Icac1af880a932b5281e9702c023d798810cf5e3d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5199218
Reviewed-by: Chris Harrelson <chrishtr@chromium.org>
Commit-Queue: Kenneth Russell <kbr@chromium.org>
Reviewed-by: Kenneth Russell <kbr@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1250977}
NOKEYCHECK=True
GitOrigin-RevId: 25d992333d6d0debd14410ca05258160a0d5b859