Skip tests that require get_computed_role on content_shell
window.test_driver_internal.get_computed_role is not implemented, so all
tests failed with TypeError: bla bla is not a function.

Skip those tests on content shell, and bring them back once chromedriver
support for content shell is ready.

Bug: 1517744
Change-Id: Iebdb754789eb7906b8a25fae9c24c946a10de138
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5189678
Reviewed-by: Chris Harrelson <chrishtr@chromium.org>
Commit-Queue: Weizhong Xia <weizhong@google.com>
Cr-Commit-Position: refs/heads/main@{#1246197}
NOKEYCHECK=True
GitOrigin-RevId: 4463ee95eae9fa376b1c4a8857dcd51fc73685aa