Revert "[breakpad] Suppress new Clang warning"
This reverts commit 0c56b41a5d238c1370bc737631f05a36340dc838
and commit 29f7552b32095c97cd75a1a6937bd2f73267c563.

Reason for revert: Possibly no longer needed after breakpad roll.

Original change's description:
> [breakpad] Suppress new Clang warning
>
> Tip-of-tree Clang warns:
>
>   ../../third_party/breakpad/breakpad/src/third_party/libdisasm/x86_format.c:836:25:
>   error: 'snprintf' will always be truncated; specified size is 32, but format
>   string expands to at least 37 [-Werror,-Wfortify-source]
>
> Suppress the warning to unblock tip-of-tree Clang until the code gets fixed.
>
> Bug: 1476401
> Change-Id: Icad1e32aa4291d2123616b4d29f53507117397e0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4814873
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Auto-Submit: Hans Wennborg <hans@chromium.org>
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1188918}

Bug: 1476401
Change-Id: I54a38fd803d818ae82ae3cb8f479985da52bd3bf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5025153
Commit-Queue: Mark Mentovai <mark@chromium.org>
Auto-Submit: Nico Weber <thakis@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Reviewed-by: Mark Mentovai <mark@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1223667}
NOKEYCHECK=True
GitOrigin-RevId: 0eaa6f8ae11538b99fab6dec7e209ef41187b725