Revert "[reland] tflite/mediapipe/eigen: avoid exposing flags to disable warnings"
This reverts commit 911d6a41bf156229df40499196ff4a4065beb4cd.

Reason for revert: Breaks compile due to new warnings:

../../components/omnibox/browser/actions/history_clusters_action.cc:64:5: error: unused function 'TransformKeywordScoreForUma' [-Werror,-Wunused-function]
   64 | int TransformKeywordScoreForUma(float keyword_score) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> [reland] tflite/mediapipe/eigen: avoid exposing flags to disable warnings
>
> This patch is exactly the same as the first. It was reverted because
> of some code not checking a return value of a function marked as
> [[nodiscard]].
>
> eigen's config contains a handful of flags that disable warnings.
> tflite was depending on this config via a public_config, which
> means any code using tflite was inheriting a bunch of flags that
> disable warnings. This is risky, and not something we should do.
>
> This patch splits eigen's config into two. The one that tflite
> depends upon via public_config does not disable any warnings. This
> means code using tflite no longer disables a bunch of compiler
> warnings. As a result of this I needed to add some flags to disable
> warnings in other code that was picking up the flags from eigen.
> That this code needs to disable warnings is not new, it was masked
> by eigen's config.
>
> This also adds -Wno-unused-function to tflite as this was masked
> by flags from eigen. Without it the following error is generated:
>
> ../../third_party/tflite/src/tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc:587:13: error: unused function 'DotprodMatrixBatchFourVectorMultiplyAccumulate' [-Werror,-Wunused-function]
> 587 | static void DotprodMatrixBatchFourVectorMultiplyAccumulate(
> |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
>
>
> Bug: 1491776
> Change-Id: Ia6dd553bd45dd44ac90b4fb0eaa9cf85890f9871
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4937388
> Commit-Queue: Scott Violet <sky@chromium.org>
> Reviewed-by: Sophie Chang <sophiechang@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1209749}

Bug: 1491776
Change-Id: Ie0581896ad12c222ee437c84baf01cf2c78a1269
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4939629
Owners-Override: Devlin Cronin <rdevlin.cronin@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Devlin Cronin <rdevlin.cronin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1209753}
NOKEYCHECK=True
GitOrigin-RevId: c3098c68481bfbe7eb5738944f80823ac80b7500