Reland "Add perf tests for WebGPU async operations"
Reland with fix: use a known unit 'ms' instead of 'ms/test'.
> ValueError: Unknown unit: "ms/test". Valid options include:
(I thought if that was going to be a problem it would be caught by CQ.)

Bug: 441525398
Original change's description:
> Revert "Add perf tests for WebGPU async operations"
>
> This reverts commit 71e1f99af212e6ac1d9463678d798716d55b11e2.
>
> Reason for revert: suspected to cause the failure of:
> benchmarks.benchmark_smoke_unittest.BenchmarkSmokeTest.blink_perf.webgpu_fast_call
>
> First failing builds on mac-13-arm64-rel-tests:
> https://ci.chromium.org/ui/p/chromium/builders/ci/mac13-arm64-rel-tests/58347/overview
>
> (Also failing on Mac12/13/14/15 bots)
>
> Bug: 441525398
> Original change's description:
> > Add perf tests for WebGPU async operations
> >
> > These simple tests reproduce issues with slow mapAsync roundtrips,
> > and provide baselines to compare against to help understand where
> > slowness occurs.
> >
> > These should appear in perf.luci.app similar to the existing benchmarks,
> > e.g.:
> > https://perf.luci.app/m/?begin=1749193837&end=1756490728&shortcut=d079629e4ccb4d1f70d5e3c4728bd739&totalGraphs=1&request_type=0
> > (Though hopefully this test runs enough iterations that it'll be less noisy than that one.)
> >
> > Locally, just start an http server in third_party/blink/perf_tests:
> > https://chromium.googlesource.com/chromium/src/+/master/docs/speed/benchmark/harnesses/blink_perf.md#running-tests
> > For slightly better results use a server that provides COOP/COEP for
> > high-precision timers (e.g. npx servez --shared-array-buffer), or use
> > chrome://flags/#isolate-origins to enable them on localhost:xxxx.
> >
> > Bug: 441525398
> > Change-Id: Iab3e2d700570290541f3bb4ccb95f44cac1eb507
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6901728
> > Auto-Submit: Kai Ninomiya <kainino@chromium.org>
> > Commit-Queue: Kai Ninomiya <kainino@chromium.org>
> > Reviewed-by: Loko Kung <lokokung@google.com>
> > Cr-Commit-Position: refs/heads/main@{#1509864}
>
> Bug: 441525398
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: Ib84ab0c975f42cc92db120ea304ca217ebf86989
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6909918
> Commit-Queue: Hiroshige Hayashizaki <hiroshige@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Auto-Submit: Hiroshige Hayashizaki <hiroshige@chromium.org>
> Owners-Override: Hiroshige Hayashizaki <hiroshige@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1509943}

Bug: 441525398
Change-Id: I845525496c45b773beac6256f0f67b70a5c3a865
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6909936
Commit-Queue: Kai Ninomiya <kainino@chromium.org>
Reviewed-by: Loko Kung <lokokung@google.com>
Commit-Queue: Loko Kung <lokokung@google.com>
Auto-Submit: Kai Ninomiya <kainino@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1509976}
NOKEYCHECK=True
GitOrigin-RevId: 3fae3be723cafda16fb55ee6766de60fae626da8