Fix node error in build in older versions of node
This is not strictly necessary for newer versions of node. In older
versions of node (v20), modules are not loaded by default, which causes
the following error:

import assert from 'node:assert/strict';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

This change is only necessary for users stuck with the older node version
so that the can get the correct error message from the version
checker script.

Change-Id: I92c916c4c8c13bb00948c81c581537ff61962306
Bug: 401522564
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6342030
Auto-Submit: Fred Shih <ffred@chromium.org>
Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
Commit-Queue: Fred Shih <ffred@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1430584}
NOKEYCHECK=True
GitOrigin-RevId: 5211137c915706f5f4f55ad343f1aa1a798dab12