[Fuchsia] prepare_package_inputs.py to support single binary
Set in python does not support `[0]` operation.

```
    binary_path = unprocessed_binary_paths[0]
TypeError: 'set' object is not subscriptable
```

Unfortunately, this scenario is not existing in the chromium, I only
caught it in flutter release & profile builds.

E.g. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8755263597772845185/+/u/build_fuchsia_profile_x64_flutter_shell_platform_fuchsia:fuchsia_flutter_shell_platform_fuchsia_dart_runner:dart_runner_tests_fuchsia_tests/stdout

Bug: 40935282
Change-Id: I8353f9dc41f17a0cf4d2912989393fa0ccafcd1d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5322168
Commit-Queue: David Song <wintermelons@google.com>
Reviewed-by: David Song <wintermelons@google.com>
Auto-Submit: Zijie He <zijiehe@google.com>
Cr-Commit-Position: refs/heads/main@{#1264823}
NOKEYCHECK=True
GitOrigin-RevId: 6fcafd6b69c3172a0cc2e4945487b3c6129e6b8d